<a href="https://colab.research.google.com/github/iamgs10rk/Introduction-to-Data-Science-in-python/blob/master/NN_All_Coding_Problems.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercise Problems 02
```
def calculate_2d_mean_median_variance_columnwise(x):
 # given a two dimensional list of numbers.
 # Calculate mean, median and variance of each column
 # x: two dimensional list of numbers
 # return: two dimensional list of 3 rows by number of columns in x
 # The first row of the return list contains mean values,
 # 2nd row contains medians and third contains variances
 # Notes:
 # IMPORTANT:
 # Use only python. No other packages such as numpy, math, …
 # Assume that all the rows of x have the same number of elements
 ```
 ```
def calculate_2d_ mean_median_variance_rowwise(x):
 # given a two dimensional list of numbers.
 # Calculate mean, median and variance of each row
 # x: two dimensional list of numbers
 # return: two dimensional list.
 # the number of rows in the return list should be the same as
 # number of rows in x and return list should have 3 columns
 # Notes:
 # Use only python. No other packages such as numpy, math, …
 # Assume that the number of elements in each row are NOT THE SAME
 ```
 ```
def column_wise_normalization(x):
# Write a function to normalize a numpy array, x, column-wise,
# by performing # the following calculation for each element:
# (element value - mean of its column) / standard deviation of its column.
```
```
def mean_absolute_error(actual,desired):
# This function calculates the mean absolute error
# between two numpy arrays.
```
```
def confusion_matrix(actual, desired):
# This function computes the confusion matrix for a multi-class
# classification problem using actual and desired values.
# actual is a numpy array [input_dimensions,nof_samples]
# desired is the same shape as actual
```
```
def covariance_matrix(X):
# This function calculates the covariance matrix
# for a given numpy array.
# Covariance Matrix = ((X-X_mean)^T* (X-X_mean))
```
[Link to Exercise Problems 02 PDF](https://ranger.uta.edu/~kamangar/CSE_5368_SP24/LinkedDocuments/CSE-5368%20Exercise%20problems%2002.pdf)


In [26]:
import numpy as np

def calculate_2d_mean_median_variance_columnwise(x):
    means = np.mean(x, axis=0)
    medians = np.median(x, axis=0)
    variances = np.var(x, axis=0)
    return [means, medians, variances]

def calculate_2d_mean_median_variance_rowwise(x):
    means = np.mean(x, axis=1)
    medians = np.median(x, axis=1)
    variances = np.var(x, axis=1)
    return np.array([means, medians, variances]).T

def column_wise_normalization(x):
    means = np.mean(x, axis=0)
    std_devs = np.std(x, axis=0)
    normalized_x = (x - means) / std_devs
    return normalized_x

def mean_absolute_error(actual, desired):
    return np.mean(np.abs(actual - desired))

def confusion_matrix(actual, desired):
    num_classes = len(np.unique(actual))
    confusion = np.zeros((num_classes, num_classes), dtype=int)
    for i in range(num_classes):
        for j in range(num_classes):
            confusion[i, j] = np.sum((actual == i) & (desired == j))
    return confusion

def covariance_matrix(X):
    return np.cov(X)

# Sample input
x = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

In [27]:
print("Input Array:")
print(x)

print("\nCalculate 2D Mean, Median, Variance Column-wise:")
result_columnwise = calculate_2d_mean_median_variance_columnwise(x)
print("Means:", result_columnwise[0])
print("Medians:", result_columnwise[1])
print("Variances:", result_columnwise[2])

print("\nCalculate 2D Mean, Median, Variance Row-wise:")
result_rowwise = calculate_2d_mean_median_variance_rowwise(x)
print(result_rowwise)

print("\nColumn-wise Normalization:")
normalized_x = column_wise_normalization(x)
print(normalized_x)

print("\nMean Absolute Error:")
actual = np.array([1, 2, 3])
desired = np.array([2, 3, 4])
mae = mean_absolute_error(actual, desired)
print(mae)

print("\nConfusion Matrix:")
actual = np.array([0, 1, 1, 2, 2, 2])
desired = np.array([0, 1, 2, 1, 2, 0])
conf_matrix = confusion_matrix(actual, desired)
print(conf_matrix)

print("\nCovariance Matrix:")
cov_matrix = covariance_matrix(x)
print(cov_matrix)

Input Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Calculate 2D Mean, Median, Variance Column-wise:
Means: [4. 5. 6.]
Medians: [4. 5. 6.]
Variances: [6. 6. 6.]

Calculate 2D Mean, Median, Variance Row-wise:
[[2.         2.         0.66666667]
 [5.         5.         0.66666667]
 [8.         8.         0.66666667]]

Column-wise Normalization:
[[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]

Mean Absolute Error:
1.0

Confusion Matrix:
[[1 0 0]
 [0 1 1]
 [1 1 1]]

Covariance Matrix:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


# Exercise Problems 07

Complete the code for the following function

import numpy as np
```
def calculate_percent_error(self, YA, YT):
    """
    Given a batch of input, actual outputs, and desired outputs, this function
    calculates percent error. For each sample, if the actual output vector is not
    exactly the same as the desired output, it is considered one error.
    Percent error is 100*(number_of_errors/ number_of_samples)
    
    :param YA: Array of actual outputs [number_of_nodes, n_samples]. Assume that
               each element of YA is either 0 or 1 (Result of hard-limit activation function).
    :param YT: Array of desired (target) outputs [number_of_nodes, n_samples].
               Assume that all the values of array YT are zero except one of them which is equal to 1.
    :return: percent_error
    """

```


https://ranger.uta.edu/~kamangar/CSE_5368_SP24/LinkedDocuments/CSE-5368%20Exercise%20problems%2007.pdf

In [28]:
import numpy as np

def calculate_percent_error(YA, YT):

    assert YA.shape == YT.shape
    error_count = np.sum(YA!=YT)
    return (error_count/YA.shape[1])*100

In [29]:

# Example input data
YA = np.array([[1, 0, 1], [0, 1, 1]])  # Actual outputs
YT = np.array([[1, 0, 1], [1, 1, 0]])  # Desired outputs

# Calculate percent error
error_percentage = calculate_percent_error(YA, YT)
print("Percent Error:", error_percentage)


Percent Error: 66.66666666666666


Complete the following code. The code should compute the output, loss, and gradients,
and perform a single weight update of a neural network with 784 inputs, 100 nodes with
sigmoid activation in the first layer, and 10 output nodes with linear activation.
Assume you have a batch of inputs called X that has dimensions [16, 784],
and a batch of targets called y that has dimensions [16, 1]

```
def my_loss(y, y_hat):
    return tf.reduce_mean(
           tf.nn.sparse_softmax_cross_entropy_with_logits(
           labels=y,logits=y_hat))
# Create random weights and biases
W_1 = tf.Variable(np.random.randn(                 ), trainable=True)
b_1 = tf.Variable(np.random.randn(                 ), trainable=True)
W_2 = tf.Variable(np.random.randn(                ), trainable=True)
b_2 = tf.Variable(np.random.randn(                 ), trainable=True)
with tf.GradientTape(persistent=True) as tape:
    # Calculate output
    output=
    # Calculate loss
    loss
    # Calculate gradients
     
    dW_1, db_1 =
     
    dW_2, db_2 =
# Calculate new values of weights and biases
```

https://ranger.uta.edu/~kamangar/CSE_5368_SP24/LinkedDocuments/CSE-5368%20Exercise%20problems%2007.pdf

In [ ]:
# Complete the following code. The code should compute the output, loss, and gradients,
# and perform a single weight update of a neural network with 784 inputs, 100 nodes with
# sigmoid activation in the first layer, and 10 output nodes with linear activation.
# Assume you have a batch of inputs called X that has dimensions [16, 784],
# and a batch of targets called y that has dimensions [16, 1]

import tensorflow as tf
import numpy as np

# Create random weights and biases
W_1 = tf.Variable(np.random.randn(784, 100), trainable=True)
b_1 = tf.Variable(np.random.randn(100), trainable=True)
W_2 = tf.Variable(np.random.randn(100, 10), trainable=True)
b_2 = tf.Variable(np.random.randn(10), trainable=True)

X = np.random.randn(16, 784)
y = np.random.randn(16, 1)

with tf.GradientTape(persistent=True) as tape:
    # Calculate output
    output = tf.sigmoid(tf.matmul(X, W_1) + b_1)
    output = tf.matmul(output, W_2) + b_2

    # Calculate loss
    loss = tf.reduce_mean(
               tf.nn.softmax(labels=tf.cast(y, dtype=tf.int32), logits=output))

    # Calculate gradients
    dW_1, db_1 = tape.gradient(loss, [W_1, b_1])
    dW_2, db_2 = tape.gradient(loss, [W_2, b_2])

# Calculate new values of weights and biases
# Define the learning rate
learning_rate = 0.01

# Update weights and biases using gradient descent
W_1.assign_sub(learning_rate * dW_1)
b_1.assign_sub(learning_rate * db_1)
W_2.assign_sub(learning_rate * dW_2)
b_2.assign_sub(learning_rate * db_2)


Complete the following function. Assume this function will be called by the main program shown below.
```
import numpy as np
import tensorflow.keras as keras
def get_biases(model, layer_number=None, layer_name=None):
“""This function returns the biases for a layer.
:param model: keras model
:param layer_number: Layer number starting from layer 0
:param layer_name: Layer name (if both layer_number and layer_name are
specified, layer number takes precedence).
:return: biases for the given layer (If the given layer does not have
bias then None should be returned)"""

my_model = keras.applications.VGG16(weights='imagenet', include_top=True)
for k in range(23):
 print(get_biases(model=my_model,layer_number=k))
 print(get_biases(model=my_model, layer_name="fc1"))
 ```
 https://ranger.uta.edu/~kamangar/CSE_5368_SP24/LinkedDocuments/CSE-5368%20Exercise%20problems%2007.pdf

In [ ]:
import numpy as np
import tensorflow.keras as keras

def get_biases(model, layer_number=None, layer_name=None):

    if layer_name is not None:
        layer = model.get_layer(layer_name)
    elif layer_number is not None:
        layer = model.layers[layer_number]
    else:
        return None

    return layer.bias.numpy() if layer.bias is not None else None

my_model = keras.applications.VGG16(weights='imagenet', include_top=True)
for k in range(23):
    print(get_biases(model=my_model, layer_number=k))
print(get_biases(model=my_model, layer_name="fc1"))


Consider a single neuron with linear activation : 𝒐𝒖𝒕𝒑𝒖𝒕 ൌ 𝑾𝒙 ൅ 𝒃
Write a Python function, using Tensorflow to adjust the weights and biases ( one
step) and return the gradients of loss with respect to 𝑾 and gradients of loss with
respect to 𝒃
Notes:
Assume loss is the defined as the MSE
You must use Tensorflow without using Keras
import tensorflow as tf
import numpy as np
```
def calculate_loss(x,y,w,b):
# x: input batch (input_dimensions, batch_size)
# y: desired output (output_dimensions, batch_size)
# w: weight matrix (input_dimensions, output_dimensions)
# b: bias (1, output_dimensions)
```
https://ranger.uta.edu/~kamangar/CSE_5368_SP24/LinkedDocuments/CSE-5368%20Exercise%20problems%2007.pdf

In [ ]:
import tensorflow as tf
import numpy as np

def calculate_loss(x, y, w, b):

    # Forward pass
    output = tf.matmul(tf.transpose(w), x) + b
    loss = tf.reduce_mean(tf.square(output - y))  # Mean Squared Error (MSE)

    # Compute gradients
    with tf.GradientTape() as tape:
        tape.watch([w, b])
        loss_value = tf.reduce_mean(tf.square(tf.matmul(tf.transpose(w), x) + b - y))
    gradients = tape.gradient(loss_value, [w, b])

    return loss, gradients[0], gradients[1]


Given the actual outputs and the desired output indexes of a neural network,
calculate and return the confusion matrix. y_hat is a matrix presenting the
actual output. Each row of this matrix is the actual output of the neural network for an input sample.

The number of rows in this matrix is equal to the number of samples in
the input batch. Y is the desired output. Each number in in the y is the index of the desired class for the corresponding input sample.

```
import numpy as np
def calculate_confusion_matrix(y_hat, y):
"""
Given the actual outputs and the desired output index of a neural
network, this function calculates the confusion matrix.
:param y_hat: Array of actual outputs [num_of samples,num_of classes]
:param y: Array of desired (target) outputs [num_of samples]. This array includes the indexes of the desired (true) class.
:return confusion_matrix[number_of_classes,number_of_classes].
Confusion matrix should be shown as the number of times that an input of class n is classified as class m."""
```
https://ranger.uta.edu/~kamangar/CSE_5368_SP24/LinkedDocuments/CSE-5368%20Exercise%20problems%2007.pdf

In [8]:
# CSE-5368 Neural Networks Fall 2022 Quiz 05

import numpy as np

def calculate_confusion_matrix(y_hat, y):

    num_classes = y.shape[0]
    confusion_matrix = np.zeros((num_classes, num_classes))
    for i in range(y_hat.shape[0]):
      confusion_matrix[i][np.argmax(y_hat[i])]  += 1
    return confusion_matrix

# Example input data
y_hat = np.array([[0.8, 0.1, 0.1],
                  [0.2, 0.7, 0.1],
                  [0.3, 0.4, 0.3]])
y = np.array([0, 1, 2])

# Calculate confusion matrix
conf_matrix = calculate_confusion_matrix(y_hat, y)

# Print confusion matrix
print("Confusion Matrix:")
print(conf_matrix)


Confusion Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]


Assuming that the actual output and the desired output of a neural network are given.
Complete the code for the following function to calculate the overall cross entropy loss for a batch of data.y_hat is a matrix presenting the actual output. Each row of this matrix is the actual output of the neural network for an input sample. The number of rows in this matrix is equal to the number of samples in the input batch. y is the desired output. Each row is a one-hot representation of the desired class. This means that all entries in each
row are zeros except one of them which is equal to 1 indicating the correct class.

Notes:
Do NOT use TensorFlow or Keras.
You may use the numpy helper functions np.nonzero() and np.log() and np.sum()
def calculate_overall_cross_entropy_loss(y_hat,y):
```
Import numpy as np
""" This function calculates the overall cross entropy loss.
layer numbers start from zero.
:param y_hat: actual output [number_of_samples,number_of_classes].
:param Y: Desired output [number_of_samples,number_of_classes].
:return: overall cross-entropy loss
"""
```
https://ranger.uta.edu/~kamangar/CSE_5368_SP24/LinkedDocuments/CSE-5368%20Exercise%20problems%2007.pdf

In [9]:
import numpy as np

def calculate_overall_cross_entropy_loss(y_hat, y):

    # Calculate cross entropy loss
    cross_entropy_loss = -np.sum(y * np.log(y_hat + 1e-15)) / len(y)

    return cross_entropy_loss

# Example usage:
# Assume y_hat and y are given
y_hat = np.array([[0.9, 0.1], [0.2, 0.8], [0.6, 0.4]])
y = np.array([[1, 0], [0, 1], [1, 0]])

# Calculate overall cross-entropy loss
loss = calculate_overall_cross_entropy_loss(y_hat, y)
print("Overall Cross-Entropy Loss:", loss)


Overall Cross-Entropy Loss: 0.2797765635793409


Consider the expression: f(x,y) = x^2 + y

Given the inputs x=2, y=5, write a Python program, using Tensorflow to
print the value of the output f(x,y) and partial derivatives of the f(x,y) with respect to x and y
```
import tensorflow as tf
import numpy as np
```
https://ranger.uta.edu/~kamangar/CSE_5368_SP24/LinkedDocuments/CSE-5368%20Exercise%20problems%2007.pdf

In [11]:
import tensorflow as tf
import numpy as np

# Define the inputs
x_value = 2
y_value = 5

# Define the variables as TensorFlow constants
x = tf.constant(x_value, dtype=tf.float32)
y = tf.constant(y_value, dtype=tf.float32)

# Define the function
def f(x, y):
    return x**2 + y

# Calculate the value of f(x, y)
output = f(x, y)

# Calculate the partial derivatives of f(x, y) with respect to x and y
with tf.GradientTape() as tape:
    tape.watch([x, y])
    output = f(x, y)

grad_x, grad_y = tape.gradient(output, [x, y])

# Print the results
print("Value of f(x, y):", output.numpy())
print("Partial derivative of f(x, y) with respect to x:", grad_x.numpy())
print("Partial derivative of f(x, y) with respect to y:", grad_y.numpy())


Value of f(x, y): 9.0
Partial derivative of f(x, y) with respect to x: 4.0
Partial derivative of f(x, y) with respect to y: 1.0


 Write a program using Tensorflow to implement a neural network with one hidden layer and one output layer.

The dimension of the input data data : 3

Number of nodes in hidden layer: 10, activation: sigmoid

Number of nodes in the output layer: 5 activation : linear

Just implement the forward path to calculate and display output. No training loop , or calculation of gradients.

https://ranger.uta.edu/~kamangar/CSE_5368_SP24/LinkedDocuments/CSE-5368%20Exercise%20problems%2007.pdf

In [12]:
import tensorflow as tf

# Define the input data
input_data = tf.constant([[1.0, 2.0, 3.0]])

# Define the weights and biases for the hidden layer
hidden_layer_weights = tf.Variable(tf.random.normal([3, 10]))
hidden_layer_bias = tf.Variable(tf.random.normal([1, 10]))

# Calculate the output of the hidden layer
hidden_layer_output = tf.sigmoid(tf.matmul(input_data, hidden_layer_weights) + hidden_layer_bias)

# Define the weights and biases for the output layer
output_layer_weights = tf.Variable(tf.random.normal([10, 5]))
output_layer_bias = tf.Variable(tf.random.normal([1, 5]))

# Calculate the output of the output layer
output = tf.matmul(hidden_layer_output, output_layer_weights) + output_layer_bias

# Print the output
print("Output of the neural network:")
print(output.numpy())


Output of the neural network:
[[ 0.8143492 -0.2766054 -2.2184353 -2.1525347 -1.2441318]]


#Fall 2021 Exam 1

Q4. Given a single-layer linear associator neural network. Complete the code for the
following function (this is similar to the function in the assignment 02).
 Only implement the delta learning 𝑾𝒏𝒆𝒘 = 𝑾𝒐𝒍𝒅 ൅ 𝜶ሺ𝒕െ𝒂ሻ𝒑𝑻
 Ignore bias
```
import numpy as np
def train(X, Y, W, batch_size, num_epochs, alpha):
""" Given a set of data points, and the hyperparameters, this function adjusts
the weights using the delta learning rule.
:param X: Array of input [input_dimensions,n_samples]
:param y: Array of desired (target) outputs [number_of_nodes,n_samples].
:param W: Array of weights (number_of_nodes,input_dimensiona)
:param num_epochs: No. of times training should be repeated over all data
:param batch_size: number of samples in a batch
:param alpha: Learning rate
:return Adjusted weights:"""
```
https://ranger.uta.edu/~kamangar/CSE_5368_SP24/LinkedDocuments/2021_10_14%20Exam1.pdf

In [ ]:
# Fall 2021 Exam 1 Q4

import numpy as np

def train(X, Y, W, batch_size, num_epochs, alpha):

    n_samples = X.shape[1]
    for epoch in range(num_epochs):
        for i in range(0, n_samples, batch_size):
            X_batch = X[:, i:i+batch_size]
            Y_batch = Y[:, i:i+batch_size]
            delta_W = alpha * (np.dot(Y_batch - np.dot(W, X_batch), X_batch.T))
            W += delta_W
    return W


Q5. Complete the following code using Tensorflow. The code should initialize the weights and biases and compute the output, loss, and gradients, and perform a single weight update of a neural network. Assume the dimension of each input sample is 400.
There are 100 nodes with sigmoid activation in the first layer, and 10 output nodes with linear activation. Loss is MSE. Assume you have a batch of inputs called X that has dimensions [20, 400], and a batch of targets called y that has dimensions [20, 10]
```
import tensorflow as tf     
import numpy as np
# Create random weights and biases
W_1 = tf.Variable(np.random.randn(                 ), trainable=True)
b_1 = tf.Variable(np.random.randn(                 ), trainable=True)
W_2 = tf.Variable(np.random.randn(                ), trainable=True)
b_2 = tf.Variable(np.random.randn(                 ), trainable=True)
with tf.GradientTape(persistent=True) as tape:
# Calculate output
output=
# Calculate loss
Loss=
# Calculate gradients
     
dW_1, db_1 =
     
dW_2, db_2 =
# Calculate new values of weights and biases
```
https://ranger.uta.edu/~kamangar/CSE_5368_SP24/LinkedDocuments/2021_10_14%20Exam1.pdf

In [ ]:
import tensorflow as tf
import numpy as np

# Dimensionality of input and output
input_dim = 400
output_dim = 10

# Create random weights and biases
W_1 = tf.Variable(np.random.randn(input_dim, 100).astype(np.float32), trainable=True)
b_1 = tf.Variable(np.random.randn(100).astype(np.float32), trainable=True)
W_2 = tf.Variable(np.random.randn(100, output_dim).astype(np.float32), trainable=True)
b_2 = tf.Variable(np.random.randn(output_dim).astype(np.float32), trainable=True)

# Assume X and y are given
X = np.random.randn(20, input_dim).astype(np.float32)
y = np.random.randn(20, output_dim).astype(np.float32)

with tf.GradientTape(persistent=True) as tape:
    # Calculate output
    hidden_output = tf.sigmoid(tf.matmul(X, W_1) + b_1)
    output = tf.matmul(hidden_output, W_2) + b_2

    # Calculate loss
    loss = tf.reduce_mean(tf.square(output - y))

# Calculate gradients
grads = tape.gradient(loss, [W_1, b_1, W_2, b_2])

# Define the learning rate
learning_rate = 0.01

# Update weights and biases using gradient descent
W_1.assign_sub(learning_rate * grads[0])
b_1.assign_sub(learning_rate * grads[1])
W_2.assign_sub(learning_rate * grads[2])
b_2.assign_sub(learning_rate * grads[3])

# Print the updated values
print("Updated weights W_1:\n", W_1.numpy())
print("Updated biases b_1:\n", b_1.numpy())
print("Updated weights W_2:\n", W_2.numpy())
print("Updated biases b_2:\n", b_2.numpy())


#Fall 2020 Exam 1 (similar)

Complete the code for the following function (this is similar to function in
assignment 01). Note that YA and YT are given
```
import numpy as np
def calculate_percent_error(YA,YT):
""" Given a batch of input, actual outputs, and desired outputs, this function
calculates percent error. For each sample, if the actual output vector is not
exactly the same as the desired output, it is considered one error. Percent
error is 100*(number_of_errors/ number_of_samples)
:param YA: Array of actual outputs [number_of_nodes, ,n_samples]. Assume that
each element of YA is either 0 or 1 (Result of hard-limit activation function).
param YT: Array of desired (target) outputs [number_of_nodes ,n_samples].
Assume that each element of YT is either 0 or 1
:return percent_error"""
```
https://ranger.uta.edu/~kamangar/CSE_5368_SP24/LinkedDocuments/2022_10_13%20Exam1.pdf

In [13]:
import numpy as np

def calculate_percent_error(YA, YT):

    num_errors = np.sum(np.any(YA != YT, axis=0))
    percent_error = 100 * num_errors / YA.shape[1]
    return percent_error

# Example usage:
# Assuming YA and YT are given
YA = np.array([[0, 1, 1, 0], [1, 0, 1, 0]])
YT = np.array([[0, 1, 0, 0], [1, 0, 1, 1]])

# Calculate percent error
error = calculate_percent_error(YA, YT)
print("Percent Error:", error)


Percent Error: 50.0


#Fall 2022 Quiz 5

Complete the following function.
Only use numpy.
DO NOT USE Tensorflow, Keras, or any other packages.
```
import numpy as np
def calculate_confusion_matrix(y_hat, y):
""" Given the actual outputs and the desired output index of a neural
network, this function calculates the confusion matrix.
:param y_hat: Array of actual outputs [num_of samples,num_of classes]
:param y: Array of desired (target) outputs [num_of samples]. This
array includes the indexes of the desired (true) class.
:return confusion_matrix[number_of_classes,number_of_classes].
Confusion matrix should be shown as the number of times that an input
of class n is classified as class m."""
```

In [15]:
import numpy as np

def calculate_confusion_matrix(y_hat, y):

    num_classes = y.shape[0]
    confusion_matrix = np.zeros((num_classes, num_classes))
    for i in range(y_hat.shape[0]):
      confusion_matrix[i][np.argmax(y_hat[i])]  += 1
    return confusion_matrix


In [16]:
# Example input data
y_hat = np.array([[0.8, 0.1, 0.1],
                  [0.2, 0.7, 0.1],
                  [0.3, 0.4, 0.3]])
y = np.array([0, 1, 2])

# Calculate confusion matrix
conf_matrix = calculate_confusion_matrix(y_hat, y)

# Print confusion matrix
print("Confusion Matrix:")
print(conf_matrix)

Confusion Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]


#Fall 2022 Exam 02 (similar)

Complete the following function using tensorflow (do not use keras) to create and train a two-layer neural network. The first layer should have 100 ReLU nodes.
The output layer should have linear nodes.
Your loss function should be mean squared error.
Anything not specified in this description should be inferred from the
function’s parameters and not hardcoded.
Code should include initializing weights, training loop with forward pass, gradient calculation, and weight updates.
You may assume the entire dataset is one batch and you do not need to split the data into batches.
```
import numpy as np
import tensorflow as tf
def create_and_train_nn(X, Y, num_epochs, alpha):
"""  
:param X: Array of input [n_samples,input_dimensions]
:param y: Array of desired (target) outputs [n_samples , target_dimension].
:param num_epochs: No. of times training should be repeated over all data
:param alpha: Learning rate:"""
```
https://ranger.uta.edu/~kamangar/CSE_5368_SP24/LinkedDocuments/2022_12_01%20Exam2.pdf

In [ ]:
import numpy as np
import tensorflow as tf

def create_and_train_nn(X, Y, num_epochs, alpha):
    """
    Create and train a two-layer neural network using TensorFlow.

    :param X: Array of input [n_samples, input_dimensions]
    :param Y: Array of desired (target) outputs [n_samples, target_dimension]
    :param num_epochs: No. of times training should be repeated over all data
    :param alpha: Learning rate
    :return: trained weights and biases
    """
    # Get input and output dimensions
    input_dim = X.shape[1]
    output_dim = Y.shape[1]

    # Initialize weights and biases
    W1 = tf.Variable(tf.random.normal([input_dim, 100]), trainable=True)
    b1 = tf.Variable(tf.zeros([100]), trainable=True)
    W2 = tf.Variable(tf.random.normal([100, output_dim]), trainable=True)
    b2 = tf.Variable(tf.zeros([output_dim]), trainable=True)

    # Training loop
    for epoch in range(num_epochs):
        # Forward pass
        with tf.GradientTape() as tape:
            # Hidden layer
            hidden_output = tf.nn.relu(tf.matmul(X, W1) + b1)
            # Output layer
            output = tf.matmul(hidden_output, W2) + b2
            # Calculate mean squared error
            loss = tf.reduce_mean(tf.square(output - Y))

        # Calculate gradients
        gradients = tape.gradient(loss, [W1, b1, W2, b2])

        # Update weights and biases
        W1.assign_sub(alpha * gradients[0])
        b1.assign_sub(alpha * gradients[1])
        W2.assign_sub(alpha * gradients[2])
        b2.assign_sub(alpha * gradients[3])

        if (epoch+1) % 100 == 0:
            print(f"Epoch {epoch+1}, Loss: {loss.numpy()}")

    return W1, b1, W2, b2

# Example usage:
# Assuming X and Y are given
X = np.random.randn(100, 10)
Y = np.random.randn(100, 5)
num_epochs = 1000
alpha = 0.01

# Train the neural network
W1, b1, W2, b2 = create_and_train_nn(X, Y, num_epochs, alpha)


#Spring 2023 Quiz 06
Complete the code for the following function.
This function is the same as the initialization part of the Assignment_01.
```
import numpy as np
def multi_layer_nn(X_train,Y_train,layers,seed=2):
# This function Initializes all the weights and
# returns weight matrices in a list
# bias should be included in the weight matrix.
# X_train: Array of input for training [input_dimensions,nof_train_samples]
# Y_train: Array of desired outputs [output_dimensions,nof_train_samples]
# layers: array of integers representing number of nodes in each layer
# return: This function should return a list of weight matrices.
# Each element of the list corresponds to the weight matrix of the
# corresponding layer.|
# Initialize the weights for each layer by:
# np.random.seed(seed)
# np.random.randn()
```
https://ranger.uta.edu/~kamangar/CSE_5368_SP24/LinkedDocuments/2023_03_09%20Quiz%2006.pdf

In [17]:
import numpy as np

def multi_layer_nn(X_train, Y_train, layers, seed=2):

    np.random.seed(seed)
    num_layers = len(layers)
    weights = []

    # Initialize weights for each layer
    for i in range(num_layers - 1):
        input_dim = layers[i]
        output_dim = layers[i + 1]
        weight_matrix = np.random.randn(output_dim, input_dim + 1)  # Add 1 for bias
        weights.append(weight_matrix)

    return weights

In [18]:
# Example usage:
X_train = np.random.randn(10, 100)  # Example input data
Y_train = np.random.randn(5, 100)   # Example output data
layers = [10, 20, 5]  # Example layer configuration

# Initialize weights
weights = multi_layer_nn(X_train, Y_train, layers)
print("Initialized weights:")
for i, weight_matrix in enumerate(weights):
    print(f"Layer {i+1}: {weight_matrix.shape}")


Initialized weights:
Layer 1: (20, 11)
Layer 2: (5, 21)


#Spring 2023 Quiz 07

Complete the code for the following function.
USE numpy only
DO NOT USE tensorflow or keras
```
import numpy as np
def calculate_svm (yhat,yt):
# This function calculates the SVM error for the entire data set
# yhat: Array of actual outputs [num_of_samples,num_of_classes]
# yt: Array of desired outputs [num_of_samples]
# Each element of yt array is the index of the true class.,
# return: SVM for the entire data set. A single float number.
# Return value is the average of all the SVMs for the samples.
# Use the following equation for SVM loss for one sample.
# Assume delta is equal to 1
```
https://ranger.uta.edu/~kamangar/CSE_5368_SP24/LinkedDocuments/2023_03_30%20Quiz%2007.pdf

In [19]:
import numpy as np

def calculate_svm_v2_my(yhat, yt):
    delta = 1
    total_loss = 0
    num_samples = yt.shape[0]
    for sample in range(num_samples):

        margin = delta + yhat[sample] - yhat[sample][yt[sample]]
        print(yhat[sample][yt[sample]])
        print(yhat[sample])
        print(margin)
        loss = np.maximum(0.0, margin)
        loss[yt[sample]] = 0

        total_loss += np.sum(loss)
    return total_loss / num_samples

In [20]:

# Example usage
yhat = np.array([[0.2, 0.3, 0.5],
                 [0.1, 0.5, 0.4],
                 [0.6, 0.2, 0.2]])
yt = np.array([0, 1, 2])  # Sample true labels

# Calculate SVM error using the provided function
svm_error = calculate_svm_v2_my(yhat, yt)

# Print the result
print("Third implementation output:", svm_error)

0.2
[0.2 0.3 0.5]
[1.  1.1 1.3]
0.5
[0.1 0.5 0.4]
[0.6 1.  0.9]
0.2
[0.6 0.2 0.2]
[1.4 1.  1. ]
Third implementation output: 2.1


#Spring 2023 Quiz 11
Using tensorflow, complete the following function to create and train a two-layer neural
network. The first layer has 12 sigmoid nodes.
The output layer has linear nodes.
Loss function should be MSE. Anything not specified in the description should be inferred
from the function’s parameters and not hardcoded.
Code should include initializing weights, training loop with forward pass, gradient
calculation, and weight updates.
You may assume the entire dataset is one batch.
```
import numpy as np
import tensorflow as tf
def create_and_train_nn(X, Y, epochs, alpha):
"""  
:param X: Array of input [n_samples,input_dimensions]
:param y: Array of desired outputs [n_samples , target_dimension].
:param epochs: number of epochs
:param alpha: Learning rate:
:return w1, w2 Weight matrices."""
```
https://ranger.uta.edu/~kamangar/CSE_5368_SP24/LinkedDocuments/2023_04_27%20Quiz%2009-14.pdf

In [ ]:
import numpy as np
import tensorflow as tf

def create_and_train_nn(X, Y, epochs, alpha):

    # Get input and output dimensions
    input_dim = X.shape[1]
    output_dim = Y.shape[1]

    # Define the number of nodes in the hidden layer
    hidden_nodes = 12

    # Initialize weights randomly
    w1 = tf.Variable(tf.random.normal([input_dim, hidden_nodes]), trainable=True)
    w2 = tf.Variable(tf.random.normal([hidden_nodes, output_dim]), trainable=True)

    # Training loop
    for epoch in range(epochs):
        # Forward pass
        with tf.GradientTape() as tape:
            # Hidden layer
            hidden_output = tf.sigmoid(tf.matmul(X, w1))
            # Output layer
            output = tf.matmul(hidden_output, w2)
            # Calculate mean squared error
            loss = tf.reduce_mean(tf.square(output - Y))

        # Calculate gradients
        gradients = tape.gradient(loss, [w1, w2])

        # Update weights using gradient descent
        w1.assign_sub(alpha * gradients[0])
        w2.assign_sub(alpha * gradients[1])

        if (epoch+1) % 100 == 0:
            print(f"Epoch {epoch+1}, Loss: {loss.numpy()}")

    return w1, w2

# Example usage:
# Assuming X and Y are given
X = np.random.randn(100, 10)  # Example input data
Y = np.random.randn(100, 5)   # Example output data
epochs = 1000
alpha = 0.01

# Train the neural network
w1, w2 = create_and_train_nn(X, Y, epochs, alpha)


#fall 2023 Exam 1
2. Complete the code for the following function.
This function is the same as the initialization part of the Assignment_01.
```
import numpy as np
def multi_layer_nn(X_train,Y_train,layers):
# This function Initializes all the weights and returns weight
# matrices in a list
# bias should be included in the weight matrix.
# X_train: Array of input for training [input_dimension,nof_train_samples]
# Y_train: Array of desired outputs [output_dimension,nof_train_samples]
# layers: array of integers representing number of nodes in each layer
# return: This function should return a list of weight matrices.
# Each element of the list should be a numpy array corresponds to the
# weight matrix of the corresponding layer.
# Initialize all the weights to zero
```
https://ranger.uta.edu/~kamangar/CSE_5368_SP24/LinkedDocuments/2023_10_12%20Exam%2001.pdf

In [21]:
import numpy as np

def multi_layer_nn(X_train, Y_train, layers):

    num_layers = len(layers)
    weights = []

    for i in range(num_layers - 1):
        input_dim = layers[i]
        output_dim = layers[i + 1]
        weight_matrix = np.zeros((output_dim, input_dim + 1))  # Add 1 for bias
        weights.append(weight_matrix)

    return weights

In [22]:

# Example usage:
X_train = np.random.randn(10, 100)  # Example input data
Y_train = np.random.randn(5, 100)   # Example output data
layers = [10, 20, 5]  # Example layer configuration

# Initialize weights
weights = multi_layer_nn(X_train, Y_train, layers)
print("Initialized weights:")
for i, weight_matrix in enumerate(weights):
    print(f"Layer {i+1}: {weight_matrix.shape}")

Initialized weights:
Layer 1: (20, 11)
Layer 2: (5, 21)


3. Using tensorflow, complete the following function to create and train a two-layer neural network. The first layer has 7 sigmoid nodes. The output layer has linear
nodes. Loss function should be MSE. Anything not specified in the description should be
inferred from the function’s arguments and not hardcoded.
Code should include initializing weights, training loop with forward pass, gradient calculation,
and weight updates.
You may assume the entire dataset is one batch.
```
import numpy as np
import tensorflow as tf
def create_and_train_nn(X, Y, epochs, alpha):
"""  
:param X: Array of input [n_samples,input_dimensions]
:param y: Array of desired outputs [n_samples , target_dimension].
:param epochs: number of epochs
:param alpha: Learning rate:
:return w1, w2 (w1 and w2 are the weight matrices after the training is done)."""
```
https://ranger.uta.edu/~kamangar/CSE_5368_SP24/LinkedDocuments/2023_10_12%20Exam%2001.pdf

In [ ]:
import numpy as np
import tensorflow as tf

def create_and_train_nn(X, Y, epochs, alpha):

    # Get input and output dimensions
    input_dim = X.shape[1]
    output_dim = Y.shape[1]

    # Define the number of nodes in the hidden layer
    hidden_nodes = 7

    # Initialize weights randomly
    w1 = tf.Variable(tf.random.normal([input_dim, hidden_nodes]), trainable=True)
    w2 = tf.Variable(tf.random.normal([hidden_nodes, output_dim]), trainable=True)

    # Training loop
    for epoch in range(epochs):
        # Forward pass
        with tf.GradientTape() as tape:
            # Hidden layer
            hidden_output = tf.nn.sigmoid(tf.matmul(X, w1))
            # Output layer
            output = tf.matmul(hidden_output, w2)
            # Calculate mean squared error
            loss = tf.reduce_mean(tf.square(output - Y))

        # Calculate gradients
        gradients = tape.gradient(loss, [w1, w2])

        # Update weights using gradient descent
        w1.assign_sub(alpha * gradients[0])
        w2.assign_sub(alpha * gradients[1])

        if (epoch+1) % 100 == 0:
            print(f"Epoch {epoch+1}, Loss: {loss.numpy()}")

    return w1, w2

# Example usage:
# Assuming X and Y are given
X = np.random.randn(100, 10)  # Example input data
X = tf.convert_to_tensor(X, dtype=tf.float64)
Y = np.random.randn(100, 5)   # Example output data
epochs = 1000
alpha = 0.01

# Train the neural network
w1, w2 = create_and_train_nn(X, Y, epochs, alpha)


#Fall 2023 Quiz 05

Do NOT use keras or Tensorflow.
Only use numpy.
```
import numpy as np
def calculate_softmax(y):
# y is a numpy array [number of samples, number_of_classes]
# Return softmax as numpy array.
[number_of_samples,number_of_classes]
```
https://ranger.uta.edu/~kamangar/CSE_5368_SP24/LinkedDocuments/2023_11_07%20Quiz%2005%20and%2006.pdf

In [24]:
import numpy as np

def calculate_softmax(y):
    # y is a numpy array [number of samples, number_of_classes]
    # Return softmax as numpy array.
    softmax_output = np.zeros((y.shape[0], y.shape[1]))
    for i in range(y.shape[0]):
      den = np.sum(np.exp(y[i]))
      for j in range(y.shape[1]):
        softmax_output[i][j] = np.exp(y[i][j])/den
        #print(softmax_output[i][j])
        #print(den)
    return softmax_output

# Example input data
input_data = np.array([[1, 2, 3], [4, 5.4, 6], [7, 8, 9.1]])

'''
1  2  3
4  5.4  6
7  8  9.1
'''

# Calculate softmax
softmax_output = calculate_softmax(input_data)

# Print output
print("Softmax Output:")
print(softmax_output)


Softmax Output:
[[0.09003057 0.24472847 0.66524096]
 [0.08035836 0.32586922 0.59377242]
 [0.08414355 0.22872589 0.68713055]]
